short_name = "Kristall"
name = "Kristall Engine"
major = 0
minor = 1
patch = 0
status = "alpha"  # alpha, beta, rc, release
module_config = "core+ai+vr"
website = "https://kristallengine.org"
docs = "https://docs.kristallengine.org/latest"
release_date = "2025-06-14"
license = "MIT"  # yoki GPL, CC va h.k.
author = "Abdulaziz Najimov"
